### PR TITLE
Please refer to the latest release on my fork or commits :)

### PR DESCRIPTION
**Pull request by meness**

### CODE REVIEW

**Comment by navinilavarasan** [comment]
What are the issues that got fixed and/or features got added?

**Comment by meness** [comment]
**Important Changes:**
- All dependencies updated to the latest stable versions
- Codes improved
- Supported APIs 27 and 28
- Dropped support from APIs 14 and 15

**Note:** Everything works properly and nothing fixed and/or features got added.

**Comment by navinilavarasan** [comment]
Thanks I will have a look at it in a couple of days.

**Comment by navinilavarasan** [comment]
I had a look at the PR.
Below was my observation:

- Looks like there has been a a lot of irrelevant changes in the PR.
Please isolate only the change for below and submit a new PR:

> All dependencies updated to the latest stable versions
> Supported APIs 27 and 28
> Dropped support from APIs 14 and 15
> 


- And for 

> Codes improved 

would suggest a different PR so that these can be merged in isolation.

- Also Saw changes to copywrite notices, would prefer to stay as is.

**Pull request closed without merging**
